agent:
    llm:
        openai:
            api_key: ${OPENAI_API_KEY}
            model: gpt-4
            timeout: 30
        provider: openai
    mcp:
        host: localhost
        metamask:
            chain_id: "1"
            enabled: true
            host: localhost
            network: Ethereum Mainnet
            port: 8083
            timeout: 30
        port: 8081
        qng:
            enabled: true
            host: localhost
            port: 8082
            timeout: 30
        timeout: 30
    name: QNG Agent
    polling:
        interval: 2
        max_attempts: 15
        timeout: 30
    version: 1.0.0
    workflow:
        max_retries: 3
        retry_delay: 5
        timeout: 300
cache:
    driver: memory
    redis:
        database: 0
        host: localhost
        password: ""
        port: 6379
        timeout: 5
database:
    driver: sqlite
    mysql:
        database: qng_agent
        host: localhost
        password: password
        port: 3306
        user: qng_agent
    postgres:
        database: qng_agent
        host: localhost
        password: password
        port: 5432
        ssl_mode: disable
        user: qng_agent
    sqlite:
        path: data/qng_agent.db
development:
    cors: true
    debug: true
    hot_reload: true
frontend:
    api:
        base_url: http://localhost:8080/api
        timeout: 30
    build_dir: ./frontend/build
    enabled: true
    host: localhost
    port: 3000
    websocket:
        enabled: true
        url: ws://localhost:8080/ws
llm:
    anthropic:
        api_key: ""
        model: claude-3-5-sonnet-20241022
        timeout: 30
    gemini:
        api_key: AIzaSyCIaQYzt085dz2saJMmAPhcoGVe-3I_Sto
        model: gemini-1.5-flash
        timeout: 30
    openai:
        api_key: ""
        base_url: https://api.openai.com/v1
        max_tokens: 2000
        model: gpt-4
        timeout: 30
    provider: gemini
logging:
    file: logs/qng_agent.log
    format: json
    level: info
    output: stdout
mcp:
    host: localhost
    metamask:
        chain_id: "1"
        enabled: true
        host: localhost
        network: Ethereum Mainnet
        port: 8083
        timeout: 30
    mode: distributed
    port: 8081
    qng:
        chain:
            enabled: true
            langgraph:
                enabled: true
                nodes:
                    - task_decomposer
                    - swap_executor
                    - stake_executor
                    - signature_validator
                    - result_aggregator
            llm:
                openai:
                    api_key: ${OPENAI_API_KEY}
                    model: gpt-4
                    timeout: 30
                provider: openai
            network: mainnet
            rpc_url: http://47.242.255.132:1234/
            transaction:
                confirmation_timeout: 60
                polling_interval: 2
                required_confirmations: 1
        enabled: true
        host: localhost
        port: 8082
        timeout: 30
    timeout: 30
monitoring:
    enabled: true
    health_check:
        enabled: true
        path: /health
        port: 8080
    metrics:
        enabled: true
        port: 9090
security:
    cors:
        enabled: true
        headers:
            - Content-Type
            - Authorization
        methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
        origins:
            - http://localhost:3000
            - http://localhost:8080
    jwt_expiry: 24h
    jwt_secret: ${JWT_SECRET}
server:
    host: 0.0.0.0
    mode: release
    port: 8080
